;/*FB_PKG_DELIM*/

__d("BladeRunnerLogger",["FBLogger","ODS"],(function(a,b,c,d,e,f,g){var h,i="bladerunner_js_client",j={info:"info",warning:"warning",exception:"exception"};a=function(){function a(){this.setFBLoggerLevel(1)}var b=a.prototype;b.info=function(a){this.$2>=2&&c("FBLogger")(i).info("BladeRunner info: %s",a),this.$3(j.info,a)};b.warn=function(a){this.$2>=1&&c("FBLogger")(i).warn("BladeRunner warn: %s",a),this.$3(j.warning,a)};b.exception=function(a,b){b===void 0&&(b="");var d=b+" "+a.toString();this.$2>=0&&c("FBLogger")(i).warn("BladeRunner exception: %s, %s",b,a.toString());this.$3(j.exception,d)};b.trimForLogging=function(a){var b=1024;return typeof a==="string"&&a.length>b?"[trimmed]:"+a.substring(0,b)+"...":a};b.bumpCounter=function(a,b){b===void 0&&(b=1),(h||(h=d("ODS"))).bumpEntityKey(2966,"BladeRunnerClient",a,b)};b.setClientSessionId=function(a){this.$1=a};b.setFBLoggerLevel=function(a){this.$2=a};b.$3=function(a,b){};return a}();b=new a();e=b;g["default"]=e}),98);
__d("FBNucleusArrowLeftFilled24Icon.react",["FBNucleusArrowLeftFilled24.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusArrowLeftFilled24.svg.react")}),98);
__d("FBNucleusArrowRightFilled24Icon.react",["FBNucleusArrowRightFilled24.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusArrowRightFilled24.svg.react")}),98);
__d("FBNucleusChevronLeftOutline20Icon.react",["FBNucleusChevronLeftOutline20.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusChevronLeftOutline20.svg.react")}),98);
__d("FBNucleusChevronLeftOutline24Icon.react",["FBNucleusChevronLeftOutline24.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusChevronLeftOutline24.svg.react")}),98);
__d("FBNucleusChevronRightOutline20Icon.react",["FBNucleusChevronRightOutline20.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusChevronRightOutline20.svg.react")}),98);
__d("FBNucleusChevronRightOutline24Icon.react",["FBNucleusChevronRightOutline24.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusChevronRightOutline24.svg.react")}),98);
__d("FBNucleusCrossFilled24Icon.react",["FBNucleusCrossFilled24.svg.react"],(function(a,b,c,d,e,f,g){g["default"]=c("FBNucleusCrossFilled24.svg.react")}),98);
__d("FDSCard.react",["FDSCardImpl.react","MetaConfig","XPlatReactEnvironment","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");b=i.forwardRef(a);function a(a,b){var e=a.background;a=babelHelpers.objectWithoutPropertiesLoose(a,["background"]);return i.jsx(c("FDSCardImpl.react"),babelHelpers["extends"]({background:e==="dark-wash"&&d("XPlatReactEnvironment").isWeb()&&c("MetaConfig")._("73")?"base-wash":e},a,{ref:b}))}a.displayName=a.name+" [from "+f.id+"]";e=b;g["default"]=e}),98);
__d("FDSLineClamp.react",["CSSUserAgentSupports","CometPlaceholder.react","CometTextTypography","FDSTextContext","JSResourceForInteraction","cr:2099","lazyLoadComponent","react","stylex","useMergeRefs"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react")),k=i,l=k.useCallback,m=k.useRef,n=k.useState;function a(){}b=(k=b("cr:2099"))!=null?k:{useTranslationKeyForTextParent:a};var o=b.useTranslationKeyForTextParent,p=c("JSResourceForInteraction")("CometTooltip_DEPRECATED.react").__setRef("FDSLineClamp.react"),q=c("lazyLoadComponent")(p),r=c("CSSUserAgentSupports").webkitLineClamp(),s={oneLine:{textOverflow:"xlyipyv",whiteSpace:"xuxw1ft",$$css:!0},root:{display:"x1lliihq",overflowX:"x6ikm8r",overflowY:"x10wlt62",position:"x1n2onr6",$$css:!0}};k=j.forwardRef(e);function e(a,b){var e=a.children,f=a.id,g=a.lines,i=a.testid,k=a.truncationTooltip;i=a.useAutomaticTextDirection;i=i===void 0?!1:i;a=a.xstyle;var u=d("FDSTextContext").useFDSTextContext(),v=o(),w=n(!1),x=w[0],y=w[1],z=m(null);w=e;var A;if(g>1)if(r)A={WebkitBoxOrient:"vertical",WebkitLineClamp:g,display:"-webkit-box"};else{e=t(u==null?void 0:u.type);A={maxHeight:e*g+.1};u={maxHeight:"calc((100% - "+e*g+"px) * 999)",top:e*(g-1)};w=j.jsxs(j.Fragment,{children:[w,j.jsx("span",{"aria-hidden":!0,className:"xds687c x6ikm8r x10wlt62 x10l6tqk",style:u,children:"\u2026"})]})}e=function(){var a=z.current;if(a==null||g<1)return;y(a.offsetWidth<a.scrollWidth||a.offsetHeight<a.scrollHeight)};u=l(function(a){if(a==null||k==null)return;p.preload()},[k]);b=c("useMergeRefs")(b,z,u);u=j.jsx("span",{className:(h||(h=c("stylex")))(s.root,g===1&&s.oneLine,a),"data-testid":void 0,dir:i?"auto":void 0,id:f,onMouseEnter:k!=null?e:void 0,ref:b,style:A,children:w},v);return x?j.jsx(c("CometPlaceholder.react"),{fallback:u,children:j.jsx(q,{tooltip:k,children:u})}):u}e.displayName=e.name+" [from "+f.id+"]";a=k;function t(a){return a!=null&&a in c("CometTextTypography")?c("CometTextTypography")[a].lineHeight:16}g["default"]=a}),98);